
export const CREATE_BLOG_REQUEST = 'CREATE_BLOG_REQUEST';
export const CREATE_BLOG_SUCCESS = 'CREATE_BLOG_SUCCESS';
export const CREATE_BLOG_FAILURE = 'CREATE_BLOG_FAILURE';

export const GET_ALLBLOGCONSTANTS_REQUEST = 'GET_ALLBLOGCONSTANTS_REQUEST';
export const GET_ALLBLOGCONSTANTS_SUCCESS = 'GET_ALLBLOGCONSTANTS_SUCCESS';
export const GET_ALLBLOGCONSTANTS_FAILURE = 'GET_ALLBLOGCONSTANTS_FAILURE';

export const GET_BLOGCONSTANTSBYID_REQUEST = 'GET_BLOGCONSTANTSBYID_REQUEST';
export const GET_BLOGCONSTANTSBYID_SUCCESS = 'GET_BLOGCONSTANTSBYID_SUCCESS';
export const GET_BLOGCONSTANTSBYID_FAILURE = 'GET_BLOGCONSTANTSBYID_FAILURE';


export const DELETE_BLOG_REQUEST = 'DELETE_BLOG_REQUEST';
export const DELETE_BLOG_SUCCESS = 'DELETE_BLOG_SUCCESS';
export const DELETE_BLOG_FAILURE = 'DELETE_BLOG_FAILURE';


export const UPDATE_BLOG_REQUEST = 'UPDATE_BLOG_REQUEST';
export const UPDATE_BLOG_SUCCESS = 'UPDATE_BLOG_SUCCESS';
export const UPDATE_BLOG_FAILURE = 'UPDATE_BLOG_FAILURE';

