// Services Constants
export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';

export const GET_ALLSERVICES_REQUEST = 'GET_ALLSERVICES_REQUEST'; 
export const GET_ALLSERVICES_SUCCESS = 'GET_ALLSERVICES_SUCCESS'; 
export const GET_ALLSERVICES_FAILURE = 'GET_ALLSERVICES_FAILURE';

export const GET_SERVICEBYID_REQUEST = 'GET_SERVICEBYID_REQUEST';
export const GET_SERVICEBYID_SUCCESS = 'GET_SERVICEBYID_SUCCESS';
export const GET_SERVICEBYID_FAILURE = 'GET_SERVICEBYID_FAILURE';

export const UPDATE_SERVICE_REQUEST = 'UPDATE_SERVICE_REQUEST';
export const UPDATE_SERVICE_SUCCESS = 'UPDATE_SERVICE_SUCCESS';
export const UPDATE_SERVICE_FAILURE = 'UPDATE_SERVICE_FAILURE';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';