
export const CREATE_TEAM_REQUEST = 'CREATE_TEAM_REQUEST';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';
export const CREATE_TEAM_FAILURE = 'CREATE_TEAM_FAILURE';

export const GET_ALLTEAMMEMBERS_REQUEST = 'GET_ALLTEAMMEMBERS_REQUEST';
export const GET_ALLTEAMMEMBERS_SUCCESS = 'GET_ALLTEAMMEMBERS_SUCCESS';
export const GET_ALLTEAMMEMBERS_FAILURE = 'GET_ALLTEAMMEMBERS_FAILURE';

export const GET_TEAMMEMBERBYID_REQUEST = 'GET_TEAMMEMBERBYID_REQUEST';
export const GET_TEAMMEMBERBYID_SUCCESS = 'GET_TEAMMEMBERBYID_SUCCESS';
export const GET_TEAMMEMBERBYID_FAILURE = 'GET_TEAMMEMBERBYID_FAILURE';

export const DELETE_TEAMMEMBER_REQUEST = 'DELETE_TEAMMEMBER_REQUEST';
export const DELETE_TEAMMEMBER_SUCCESS = 'DELETE_TEAMMEMBER_SUCCESS';
export const DELETE_TEAMMEMBER_FAILURE = 'DELETE_TEAMMEMBER_FAILURE';

export const UPDATE_TEAMMEMBER_REQUEST = 'UPDATE_TEAMMEMBER_REQUEST';
export const UPDATE_TEAMMEMBER_SUCCESS = 'UPDATE_TEAMMEMBER_SUCCESS';
export const UPDATE_TEAMMEMBER_FAILURE = 'UPDATE_TEAMMEMBER_FAILURE';

